#include <stdio.h>
#include <stdlib.h>
#include "headers/token.h"
#include "headers/linked_list.h"

FILE *input_file = NULL;
FILE *output_file = NULL;

extern FILE *yyin;
extern FILE *yyout;
extern int   yylineno;
extern int   tokenNumber;

/**
 * Generated By Flex
 */
int alpha_yylex(void *yylval);

/**
 * @return 1 if everything is successfull , -1 if an error occured caller must terminate the program.
 */
static int open_files(int argc, char *args[])
{
    if (argc < 2)
    {
        fprintf(stderr, "[ERROR]: 1-2 Arguments are required, ./%s <input_file> ?<output_file>\n", args[0]);
        return -1;
    }
    input_file = fopen(args[1], "r");
    if (!input_file)
    {
        fprintf(stderr, "[ERROR]: Error opening input file named: %s\n", args[1]);
        return -1;
    }

    // no output file = NULL
    if (argc < 3)
    {
        output_file = stdout;
        return 1;
    }

    output_file = fopen(args[2], "w");
    if (!input_file)
    {
        fprintf(stderr, "[ERROR]: Error opening output file named: %s\n", args[2]);
        return -1;
    }
    return 1;
}

static void close_files()
{
    if (input_file)
        fclose(input_file);

    if (output_file && output_file != stdout)
        fclose(output_file);
}

int main(int argc, char *args[])
{
    List *token_list;

    if (open_files(argc, args) < 0)
        return -1;

    yyin = input_file;
    yyout = output_file;

    if (LinkedList_CreateEmpty(&token_list) <= 0)
        return -1;

    Token return_token;
    while (alpha_yylex((void *)&return_token) >= 0)
        if(LinkedList_AddToEnd(&token_list, return_token) <= 0)
            return -1;

    LinkedList_Print(token_list, output_file);
    printf("[LEXER] Reached end of file at line %d\n", yylineno);
    printf("[LEXER] Lexical analysis identified %d tokens.\n", tokenNumber);

    close_files();
    return 0;
}